# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 21:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureReserveFound',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('prot_class', models.CharField(max_length=80, null=True)),
                ('prot_stat', models.CharField(max_length=80, null=True)),
                ('prot_title', models.CharField(max_length=99, null=True)),
                ('amenity', models.CharField(max_length=80, null=True)),
                ('leisure', models.CharField(max_length=80, null=True)),
                ('landuse', models.CharField(max_length=80, null=True)),
                ('historic', models.CharField(max_length=80, null=True)),
                ('tourism', models.CharField(max_length=80, null=True)),
                ('website', models.CharField(max_length=110, null=True)),
                ('wikipedia', models.CharField(max_length=103, null=True)),
                ('note', models.CharField(max_length=80, null=True)),
                ('area', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TransalteName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=177, null=True)),
                ('name_uk', models.CharField(max_length=177, null=True)),
                ('name_ru', models.CharField(max_length=177, null=True)),
                ('name_en', models.CharField(max_length=177, null=True)),
            ],
        ),
    ]
