# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wcs', '0002_naturereservefound_transaltename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('style_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('legend', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='NatureReserveFound',
            new_name='Nature_Reserve_Found',
        ),
        migrations.RenameModel(
            old_name='TransalteName',
            new_name='Transalte_Name',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='shapefile',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='id',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='shapefile',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='type',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='width',
        ),
        migrations.AddField(
            model_name='attribute',
            name='db_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_geoserver',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='req',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='sql',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='translate_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='wms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Shapefile',
        ),
    ]
